version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/common/Dockerfile
      target: production
      args:
        - UID=${DOCKER_UID:-1000}
        - GID=${DOCKER_GID:-33}
        - USER_NAME=${DOCKER_USER:-isl}
        - GROUP_NAME=${DOCKER_GROUP:-www-data}
    ports:
      - "${APP_PORT_IN_HOST_SERVER}:80"
    restart: unless-stopped
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - laravel

networks:
  laravel:

volumes:
  laravel-storage:
  sqlite-data:
