version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/common/Dockerfile
      target: production
      args:
        - UID=1000
        - GID=33
    ports:
      - "8084:80"
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./database:/var/www/database
    environment:
      - APP_ENV=production
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - laravel

networks:
  laravel:

volumes:
  laravel-storage:
  sqlite-data:
